import { readdirSync, rmdirSync } from 'fs';
import { repo } from './developer';
const { cwd, chdir } = process;
import { success, warning, error, prettify } from '../lib/js/helpers/prettify';

// cd into repo root
chdir('../');

// use repo root
const rootDir = cwd();

// return all files and folders in repo root i.e. original + create-collabo-app generated
 const repoContent = readdirSync(rootDir, (err, filesAndFolders) => {
    if (err) {
      throw err;
    }

    return filesAndFolders;
});

const filterContentToGetTheOnesGeneratedByCLI = repoContent.reduce((acc, curr) => {
  if (!repo.originalContentList.includes(curr)) {
    acc.push(curr);
  }
  return acc;
}, []);

// delete folders generated by CLI
if (filterContentToGetTheOnesGeneratedByCLI.length) {
  try {
    filterContentToGetTheOnesGeneratedByCLI.map(folder => {
      success(`✔ ${folder} folder deleted successfully`);
      return rmdirSync(folder, { recursive: true, force: true });
    });
    prettify.log.color.none('');
  } catch (err) {
    error(err);
  }
} else {
  warning('ℹ There are no project folders to delete yet. Generate project folder(s) using the "collabo-be" command, then run the cleanup script after you are done developing, and are ready to add and push your changes/fixes to GitHub.\n');
}

